# Change these first
owner: rgstephens # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: tonk.link
    url: https://tonk.link
  - name: play.tonk.link
    url: https://play.tonk.link
  - name: Golftrip
    url: https://golftrip.link
  - name: Avkana
    url: https://avkana.com
  - name: gstephens
    url: https://gstephens.org
  - name: BGC
    url: https://broadmoorgolfclub.com
  - name: BHA
    url: https://broadmoorhomeowners.com
  - name: MDI Maui
    url: https://mdimaui.com
  - name: Natmed
    url: https://natmed.net
  - name: FishOn
    url: https://fishonwithjon.com
  - name: Cryptoagent
    url: https://cryptoagent.us
  - name: RasaAlerts
    url: https://rasaalerts.com
  - name: Bandon Brawl
    url: https://bandonbrawl22.com
  - name: RasaBot
    url: https://rasabot.us
  - name: minio-ui
    url: https://minio-ui.gstephens.org
  # - name: JokeBot Status endpoint
  #   # https://rasa.com/docs/rasa/http-api#security-considerations
  #   url: https://jokebot.rasabot.us/status
  #   expectedStatusCodes:
  #     - 401
  #   __dangerous__body_down_if_text_missing: '"version":'
  - name: Jokebot REST endpoint
    url: https://jokebot.rasabot.us/webhooks/rest
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: '"status":"ok"'
  # - name: RISbot Status endpoint
  #   url: https://risbot.rasabot.us/status
  #   expectedStatusCodes:
  #     - 401
  #   __dangerous__body_down_if_text_missing: '"version":'
  - name: RISbot REST endpoint
    url: https://risbot.rasabot.us/webhooks/rest
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: '"status":"ok"'
  # - name: Financial Demo Status endpoint
  #   url: https://financialbot.rasabot.us/status
  #   expectedStatusCodes:
  #     - 401
  #   __dangerous__body_down_if_text_missing: '"version":'
  - name: Financial Demo REST endpoint
    url: https://financialbot.rasabot.us/webhooks/rest
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: '"status":"ok"'
  - name: Haystack Demo REST endpoint
    url: https://haystackbot.rasabot.us/webhooks/rest
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: '"status":"ok"'


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: status.stephens.link
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Stephens** status page"
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: ocean

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
